sudo: required
dist: trusty
language: python

python:
    - "3.5"

# command to install dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential git cmake libfreeimage-dev cmake-curses-gui
    - sudo apt-get install -qq libopenblas-dev libfftw3-dev liblapacke-dev libboost-all-dev
    - sudo apt-get install -qq libfontconfig1-dev
    - sudo apt-get install build-essential cmake cmake-curses-gui xorg-dev libglu1-mesa-dev libxinerama-dev libxcursor-dev
    - grep MemTotal /proc/meminfo
    - cat /proc/cpuinfo
    - wget https://github.com/glfw/glfw/archive/3.1.2.zip -O glfw-3.1.2.zip
    - unzip glfw-3.1.2.zip
    - cd glfw-3.1.2
    - mkdir build
    - cd build
    - cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
    - make -j8
    - sudo make install
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH 
    - cd ../../
    - wget https://fs1.transfernow.net/download/5a62d6a6d1844/master/arrayfire.tar.gz
    - tar xzf arrayfire.tar.gz
    - cd arrayfire-3
    - export AF_PATH=$PWD
    - cd lib
    - export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
    - cd ../../
    - #git clone https://github.com/arrayfire/arrayfire.git
    - #cd arrayfire
    - #git submodule init
    - #git submodule update
    - #mkdir build 
    - #cd build
    - #cmake .. -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=package -DBUILD_GRAPHICS=OFF
    - #make -j8
    - #sudo make install
    - #cd package
    - #export AF_PATH=$PWD
    - #cd lib
    - #export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
    - #echo $LD_LIBRARY_PATH
    - #cd ../../../../
    - wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.8.3.tar.gz
    - tar xzf petsc-3.8.3.tar.gz
    - cd petsc-3.8.3
    - python2 './configure' '--with-debugging=0' '--with-mpi=1' '--with-hdf5' '--download-hdf5' '--download-f2cblaslapack'
    - make PETSC_DIR=/home/travis/build/ShyamSS-95/Bolt/petsc-3.8.3 PETSC_ARCH=arch-linux2-c-opt all
    - export PETSC_DIR=/home/travis/build/ShyamSS-95/Bolt/petsc-3.8.3
    - export PETSC_ARCH=arch-linux2-c-opt
    - cd ..
    - pip install virtualenv
    - virtualenv venv 
    - source venv/bin/activate

install:
    - pip install -r requirement.txt

# command to run tests
# TODO: Include unit tests here.
# May need to write installer before that
script:
    - python -c 'import bolt'
