sudo: required
dist: trusty
language: python

python:
    - "3.5"

env:
    - AF_PATH="$HOME/arrayfire-3"
    - LD_LIBRARY_PATH="$AF_PATH/lib:$LD_LIBRARY_PATH"
    - PYTHON_PATH="$HOME/Bolt/:$PYTHON_PATH"

# command to install dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential git cmake libfreeimage-dev cmake-curses-gui
    - sudo apt-get install -qq libopenblas-dev libfftw3-dev liblapacke-dev libboost-all-dev
    - wget http://arrayfire.s3.amazonaws.com/3.5.0/ArrayFire-v3.5.0_Linux_x86_64.sh
    - bash ArrayFire-v3.5.0_Linux_x86_64.sh

install:
    - pip install -r requirements.txt

# command to run tests
script: py.test lib/linear_solver/tests