time mpiexec -n 1 python main.py 
time mpiexec -n 2 python main.py 
time mpiexec -n 3 python main.py 
time mpiexec -n 4 python main.py 
time mpiexec -n 5 python main.py 
time mpiexec -n 6 python main.py 
time mpiexec -n 7 python main.py 
time mpiexec -n 8 python main.py 
time mpiexec -n 9 python main.py 
time mpiexec -n 10 python main.py 
time mpiexec -n 11 python main.py 
time mpiexec -n 12 python main.py 
time mpiexec -n 13 python main.py 
time mpiexec -n 14 python main.py 
time mpiexec -n 15 python main.py 
time mpiexec -n 16 python main.py 
time mpiexec -n 17 python main.py 
time mpiexec -n 18 python main.py 
time mpiexec -n 19 python main.py 
time mpiexec -n 20 python main.py 
time mpiexec -n 21 python main.py 
time mpiexec -n 22 python main.py 
time mpiexec -n 23 python main.py 
time mpiexec -n 24 python main.py 
time mpiexec -n 25 python main.py 
time mpiexec -n 26 python main.py 
time mpiexec -n 27 python main.py 
time mpiexec -n 28 python main.py 
time mpiexec -n 29 python main.py 
time mpiexec -n 30 python main.py 
time mpiexec -n 31 python main.py 
time mpiexec -n 32 python main.py 
time mpiexec -n 33 python main.py 
time mpiexec -n 34 python main.py 
time mpiexec -n 35 python main.py 
time mpiexec -n 36 python main.py 
time mpiexec -n 37 python main.py 
time mpiexec -n 38 python main.py 
time mpiexec -n 39 python main.py 
time mpiexec -n 40 python main.py 
time mpiexec -n 41 python main.py 
time mpiexec -n 42 python main.py 
time mpiexec -n 43 python main.py 
time mpiexec -n 44 python main.py 
